name: Kim Thoenen
description: Writing about stuffs
meta_description: "I write about things I'm interested in - if I find the time"

markdown: kramdown
highlighter: Rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://chive.ch'
google_analytics: 'UA-62795232-5'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://chive.ch'
author:         'Kim Thoenen'
